// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnedkxjlmcnarvajtfyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZuZWRreGpsbWNuYXJ2YWp0ZnlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMzU1ODMsImV4cCI6MjA2MDkxMTU4M30.ShxorgCbDo4bA0Sbv1Upjf-GZIiZBQ4x0oO9GrXyUX4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);